### ISSUE TITLE
To-Do List:

### ISSUE THREAD

**Issue by deavmi** [deavmi/Picy#21]
This is the to-do list for **v1**:

- [ ] Generate site function (`gen`)
- [ ] Usage function (`displayHelp`)
- [ ] Check if recipe exists function (`checkRecipePath`)
- [ ] Placeholder variable value assigner (`setPlaceholderVals`)
- [ ] Check for variables in recipe; the requirements must be met (`checkVars`)
- [ ] This function (`getVars`)
- [ ] Page creation function (`createPage`)
- [ ] Arguments parsing function (`checkArgs`) [Issue: https://github.com/deavmi/Picy/issues/5]

- [ ] Stop coding this and install Trisquel.
